In [4]:
# 1. Create a 2D array of shape (5,5) filled with random numbers between 10 and 50. Replace all the numbers greater than 40 with -1 without using a loop.

# 2. Create a 1D array and reshape it into a 3D array of shape (2,3,4). Then swap the axes 0 and axes 2 using the swapaxes method.

# 3. Subtract the mean of each column from the respective column elements in a 2D (take a 3*3 shape) array

# 4. Multiply each row of a matrix by a different scalar given in a 1D array

# 5. From a random array of size 20, extract values greater than 30 and divisible by 3

# 6. Replace all the negative values in a 2D array with the row-wise maximum value.

# 7. Sort a 2D array based on the values of the second column.

# 8. Filter the element 'High' if the value is >50 and otherwise 'Low'.

# 9. Create an array of a range between 1 and 100, normalise it into the range 0 to 1.

In [5]:
# 1. Create a 2D array of shape (5,5) filled with random numbers between 10 and 50. Replace all the numbers greater than 40 with -1 without using a loop.

import numpy as np

arr = np.random.randint(10,50, size = (5,5))
arr[arr> 40] = -1
# np.where(arr>40, -1, arr)
print(arr)

[[22 27 33 28 -1]
 [37 25 -1 37 40]
 [23 18 10 12 31]
 [15 32 27 10 17]
 [23 -1 -1 13 13]]


In [6]:
# 2. Create a 1D array and reshape it into a 3D array of shape (2,3,4). Then swap the axes 0 and axes 2 using the swapaxes method.

arr = np.arange(24).reshape(2,3,4)
print(arr,'\n','-'*20)
swapped = np.swapaxes(arr, 0, 2)     #np.swapaxes(arr, axis 1, axis 2)
print(swapped)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 
 --------------------
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


In [7]:
# 3. Subtract the mean of each column from the respective column elements in a 2D (take a 3*3 shape) array

arr = np.random.randint(1,20, size=(3,3))
col_mean = np.mean(arr, axis=0)            #mean of each column
result = arr - col_mean
print(result)

[[-9.          8.         -3.33333333]
 [ 7.         -3.         -3.33333333]
 [ 2.         -5.          6.66666667]]


In [8]:
# 4. Multiply each row of a matrix by a different scalar given in a 1D array

arr1 = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
arr2 = np.array([10,15,20])          #(3,)
result = arr1 * arr2[:, None]        #(3,1)
print(result)

[[[ 10  20  30]
  [ 60  75  90]
  [140 160 180]]]


In [9]:
# 5. From a random array of size 20, extract values greater than 30 and divisible by 3.

arr = np.random.randint(1,50,size=20)
arr[(arr>30) & (arr%3==0)]
print(arr)

[23  4 36  8 26 27 43 11 21 12 18 39 41 34 17 29  2 32 11 38]


In [10]:
# 6. Replace all the negative values in a 2D array with the row-wise maximum value.

arr = np.random.uniform(-20, 50, size=(2,2))

print(f'Initial array:\n{arr}')
print('-'*30)

row_max = arr.max(axis=0)
arr = np.where(arr<0, row_max, arr)
print(f'Final array:\n{arr}')

Initial array:
[[10.19233964 48.26103806]
 [16.06102616 -5.61489524]]
------------------------------
Final array:
[[10.19233964 48.26103806]
 [16.06102616 48.26103806]]


In [11]:
# 7. Sort a 2D array based on the values of the second column.

arr = np.random.randint(1,20,(3,3))
sorted_array = arr[arr[:,1].argsort()]
print(f'Initial array:\n{arr}\n{'-'*20}')
print(f'Sorted array:\n{sorted_array}')

Initial array:
[[ 3  6 19]
 [ 9 16  3]
 [15 15 19]]
--------------------
Sorted array:
[[ 3  6 19]
 [15 15 19]
 [ 9 16  3]]


In [12]:
# 8. Filter the element 'High' if the value is >50 and otherwise 'Low'.

# arr = np.array([10,15,18,30,25])
# print(np.where(arr >= 18, 'Can drive', 'Can\'t drive'))

arr = np.random.randint(0,100,15)
print(np.where(arr>50, 'High', 'Low'))

['Low' 'High' 'High' 'Low' 'High' 'High' 'High' 'High' 'Low' 'High' 'Low'
 'Low' 'High' 'High' 'High']


In [15]:
# 9. Create an array of a range between 1 and 100, normalise it into the range 0 to 1.

arr = np.arange(0,101)
print("Original array:\n", arr)

normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print("\nNormalized array:\n", normalized)

Original array:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]

Normalized array:
 [0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]
