In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
#Random numbers
#random.rand()

import numpy as np
arr = np.random.rand(3,4)
print(arr)

[[0.31911215 0.86400633 0.74166129 0.11566864]
 [0.43247523 0.18713545 0.07136313 0.87118418]
 [0.3431625  0.36317545 0.52082211 0.39237039]]


In [2]:
arr1 = np.random.rand(2,2)
print(arr1)

[[0.92933913 0.89570778]
 [0.57364729 0.71716327]]


In [4]:
arr1.ndim

2

In [16]:
#random.randn

arr = np.random.randn(3,3)
print(arr)

[[ 0.02295244  0.61343248  0.44636846]
 [-1.25441514 -0.21109688 -1.27053982]
 [ 1.36212375  0.02879261  1.4115997 ]]


In [261]:
#random.randint

arr = np.random.randint(10,50,(3,8))
print(arr)

[[40 34 25 10 28 44 35 36]
 [35 31 11 32 41 15 22 41]
 [38 28 14 18 32 47 11 39]]


In [314]:
#random.uniform

arr = np.random.uniform(10,50,5)
print(arr)

[30.13639277 49.46345207 24.69868653 40.95823644 28.66495321]


In [316]:
arr = [[1,2,3],[4,5,6]]
arr[0][2]

3

In [318]:
#indexing & slicing

# 1-D

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [319]:
print(arr[1])

2


In [320]:
print(arr[-1])

5


In [321]:
# 2-D

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [324]:
print(arr[0,2])

3


In [325]:
print(arr[0])

[1 2 3]


In [328]:
print(arr[:,1])

[2 5]


In [335]:
print(arr[0,:])

[1 2 3]


In [346]:
print(arr[0:2, 0:2])

[[1 2]
 [4 5]]


In [350]:
# 3-D

arr = np.array([[[1,2],[3,4],[5,6]]])
print(arr)

[[[1 2]
  [3 4]
  [5 6]]]


In [352]:
print(arr[:,0])

[[1 2]]


In [377]:
print(arr[0,0:,0])

[1 3 5]


In [379]:
#Boolean slicing

arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [381]:
print(arr[arr>30])

[40 50]


In [385]:
print(arr[(arr>30) & (arr<50)])

[40]


In [387]:
arr[3] = 400
print(arr)

[ 10  20  30 400  50]


In [388]:
arr[arr>30] = 0
print(arr)

[10 20 30  0  0]


In [392]:
#append

print(np.append(arr, 60))

[10 20 30  0  0 60]


In [394]:
#insert

print(np.insert(arr, 3, 40))

[10 20 30 40  0  0]


In [397]:
#delete

print(np.delete(arr, 4))

[10 20 30  0]


In [398]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [403]:
arr1 = arr.reshape(3,4)

In [404]:
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [406]:
print(arr1.ravel())      #view

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [410]:
arr = arr1.flatten()
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [411]:
arr1.T   #transpose

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [426]:
# Create a 1D array from 1 to 20. Print all the even numbers

arr = np.array(range(21))
print(arr[arr%2==0])

[ 0  2  4  6  8 10 12 14 16 18 20]


In [464]:
# Create a 4*4 array of random numbers and get the 2nd and 3rd columns using slicing

arr = np.random.randint(10,50,(4,4))
print(arr)

[[39 44 17 25]
 [13 28 27 26]
 [22 40 31 19]
 [46 21 13 38]]


In [465]:
print(arr[0:, 0:2])

[[39 44]
 [13 28]
 [22 40]
 [46 21]]


In [445]:
# Generate 5 random decimal numbers between 50 and 60 and get the element greather than 55