In [2]:
import numpy as np

In [3]:
''' Numpy '''

' Numpy '

# 1. Describe the features of numpy.
   
Ans:
1. N‑Dimensional Array Object (ndarray)
- 1D (vectors)
- 2D (matrices)
- Higher dimensions (tensors)

2. Vectorised Operations - NumPy performs operations on entire arrays without loops.
This makes computations: Faster, Cleaner (Eg, a+b)

3. Broadcasting - Broadcasting lets NumPy apply operations between arrays of different shapes.

4. Mathematical and Statistical Functions - NumPy includes a huge collection of optimised functions: Mean, median, std, var, 
Trigonometric functions, Linear algebra operations, Random number generation.

5. Memory Efficiency - NumPy arrays store data in contiguous memory blocks, making them: Faster to access, more compact than Python lists.

6. Integration with Other Libraries - Pandas, SciPy, TensorFlow, etc

7. Linear Algebra Support - NumPy provides: Matrix multiplication, Determinants, Eigenvalues, Inverses

8. Random Module - numpy.random offers: Random numbers, Sampling, Probability distribution, Shuffling

9. Universal Functions (ufuncs) - np.sqrt(), np.exp(), np.log()

10. Reshaping and Manipulating Arrays - NumPy makes it easy to: Reshape, Flatten, Split, Stack, Transpose

# 2. Write the applications of numpy.

Ans: Applications of NumPy

1. Data Analysis: Cleaning and transforming data, handling missing values, performing fast mathematical operations, serving as the underlying structure for Pandas

2. Scientific Computing - Physics simulations, Statistical computations, etc.

3. Machine Learning & AI - Feature scaling, normalisation, and preprocessing, handling large datasets efficiently.

4. Linear Algebra & Matrix Operations - Matrix multiplication, Determinants and inverses, Solving systems of equations.

5. Statistics & Probability - Mean, median, variance, standard deviation, probability distributions.

6. Image Processing - Pixel manipulation, filtering and resizing.

7. Signal Processing - Fourier transforms, filtering signals, time‑series manipulation

8. Financial Modelling - Portfolio optimisation, risk analysis, option pricing, time-series forecasting.

# 3. How numpy is different from python sequences.

Key Differences Between NumPy Arrays and Python Sequences are:

1. Data Type (Homogeneous vs Heterogeneous) - 
NumPy arrays:
 - Store only one data type (all elements must be integers, floats, etc.)
 - This uniformity makes them fast and memory‑efficient.
Python sequences (lists/tuples):
 - Can store mixed data types (int, float, string, object).
 - More flexible but slower.

2. Memory Efficiency
NumPy arrays:
 - Stored in contiguous memory blocks, enabling fast access and computation.
 - Much more compact than Python lists.
Python lists:
 - Store references to objects scattered in memory.
 - Consume more memory.

3. Speed and Performance
NumPy arrays:
 - Optimized in C; operations run at compiled speed.
 - Support vectorized operations (operate on entire arrays without loops).
Python lists:
 - Operations require Python loops, which are slow.
 - No vectorization.

4. Mathematical Operations
NumPy arrays:
 - Support element‑wise operations directly:
 - a+b
 - a*5
 - Rich set of mathematical, statistical, and linear algebra functions.
Python lists:
 - Do not support element‑wise math:
 - [1,2,3] * 2  # repeats list, not multiply
 - Need loops or list comprehensions for math.

5. Broadcasting
NumPy arrays:
 - Can automatically expand dimensions to perform operations between arrays of different shapes.
Python lists:
 - No broadcasting support.

6. Multi‑Dimensional Support
NumPy arrays:
 - Support n‑dimensional arrays (2D, 3D, tensors).
Python lists:
 - Can nest lists, but operations become slow and complicated.

7. Built‑in Functions
NumPy arrays:
 - Provide functions like mean(), sum(), std(), dot(), etc.
Python lists:
 - Only basic operations; need loops or external libraries for math.

Summary: 
NumPy arrays differ from Python sequences in several ways: they are homogeneous, memory‑efficient, 
and stored in contiguous blocks, making them much faster for numerical operations. 
NumPy supports vectorisation, broadcasting, and multi‑dimensional arrays, while Python sequences are heterogeneous, 
slower, and lack built‑in mathematical capabilities.

In [4]:
# 4. Create two 1-D arrays with numbers and strings respectively.

arr_num = np.array([1,2,3,4])
arr_str = np.array(['a', 'b', 'c', 'd'])
print(arr_num)
print(arr_str)

[1 2 3 4]
['a' 'b' 'c' 'd']


In [5]:
# 5. Create 2-D and 3-D arrays. And check their shape and dimensions using (shape and ndim methods).

arr2d = np.random.randint(0,10,(2,2))
arr3d = np.random.randint(0,50, (1,3,3))
print(f'2D shape: {np.shape(arr2d)}')
print(f'2D array dimensions: {np.ndim(arr2d)}')
print(f'3D shape: {np.shape(arr3d)}')
print(f'3D array dimensions: {np.ndim(arr3d)}')

2D shape: (2, 2)
2D array dimensions: 2
3D shape: (1, 3, 3)
3D array dimensions: 3


# 6. Explain Data Analysis in your own words using a markdown cell.

Ans. Data analysis is the process of collecting, cleaning, organizing, and examining data to discover useful information. 
It helps us understand patterns, relationships, and trends hidden inside raw data. 
By applying different statistical and analytical techniques, we can turn messy data into meaningful insights 
that support better decision‑making. In simple terms, data analysis transforms data into knowledge.

In [6]:
''' Creation of numpy with different methods '''

' Creation of numpy with different methods '

In [7]:
# 7. Create a 1D NumPy array with elements from 1 to 10 using arange().

arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [8]:
# 8. Create a 2D array of size 3x3 filled with zeros using zeros().

arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# 9. Create an array [5, 10, 15, 20, 25]. Find its size, item size, and total bytes used by the array.

arr = np.array([5, 10, 15, 20, 25])
print(f'Size: {arr.size}')
print(f'Item size: {arr.itemsize}')
print(f'Total bytes: {arr.nbytes}')

Size: 5
Item size: 8
Total bytes: 40


In [10]:
# 10. Use linspace() to generate an array of 7 equally spaced numbers between 0 and 14.

arr = np.linspace(0,14,7)
print(arr)

[ 0.          2.33333333  4.66666667  7.          9.33333333 11.66666667
 14.        ]


In [11]:
# 11. Create a 4x4 identity matrix using eye().

print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
# 12. Create a 3x3 diagonal matrix with the diagonal values [1, 2, 3] using diag().

print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [13]:
# 13. Create a 2x3 array filled with the value 9 using full().

arr = np.full((2,3),7)
print(arr)

[[7 7 7]
 [7 7 7]]


In [15]:
# 14. Generate a 3x3 array of random numbers between 0 and 1 using random.rand().

arr = np.random.rand(3,3)
print(arr)

[[0.01101867 0.80602123 0.37259794]
 [0.19926055 0.47944375 0.08471949]
 [0.05924467 0.6639731  0.13471307]]


In [18]:
# 15. Create a 4x4 array of random integers between 10 and 50 using random.randint().

arr = np.random.randint(10,50,(4,4))
print(arr)

[[11 20 43 47]
 [41 36 37 37]
 [47 39 29 35]
 [47 42 49 45]]


In [25]:
# 16. Generate a 1D array of 5 random numbers from a normal distribution using random.randn().

arr = np.random.randn(5)
print(arr)

[-0.4640705  -0.01877748  2.2976455  -2.22599566  0.52549147]


In [26]:
# 17. Generate a 2D array of shape (2, 4) with random values uniformly distributed between -5 and 5 using random.uniform().

arr = np.random.uniform(-5,5,(2,4))
print(arr)

[[ 4.52484557 -4.09785447 -4.31192765 -3.94159236]
 [ 2.0054086   0.58294678 -2.89650253 -2.57052879]]


In [32]:
# 18. Create a 1D array [10, 20, 30, 40, 50]. Access the third element and update it to 35.

arr = np.array([10,20,30,40,50])
arr[2] = 35
print(arr)

[10 20 35 40 50]


In [51]:
# 19. Create a 2D array of shape (3, 4) with values from 1 to 12. Slice and extract the second row.

arr = np.arange(1,13).reshape(3,4)
print(arr,'\n')
print(arr[1,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[5 6 7 8]


In [52]:
# 20. From the same array, extract all elements in the last column.

print(arr[:,-1])

[ 4  8 12]


In [57]:
# 21. Create a 3x3 array of ones using ones() and change its dtype to int.

arr = np.ones((3,3),dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [60]:
# 22. Create an array [1, 2, 3, 4, 5] and multiply each element by 2.

arr = np.array([1, 2, 3, 4, 5])
print(arr*2)

[ 2  4  6  8 10]


In [61]:
''' Numpy Methods '''

' Numpy Methods '

In [73]:
# 23. Create a 1D NumPy array with values from 1 to 10. Access the elements at indices 2, 5, and 7

arr = np.arange(1,11)
print(arr[[2,5,7]])

[3 6 8]


In [76]:
# 24. Given an array `arr = np.array([10, 20, 30, 40, 50, 60, 70])`, extract a slice that contains the elements from index **2 to 5**.

arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[2:6])

[30 40 50 60]


In [109]:
# 25. Create an array of 10 random integers between 1 and 20. Extract all elements greater than 10.

np.random.seed(42)

arr = np.random.randint(1,20,10)
print(arr)

print(arr[arr>10])

[ 7 15 11  8  7 19 11 11  4  8]
[15 11 19 11 11]


In [111]:
# 26. Create a NumPy array of size 6.

arr = np.arange(0,6)
print(arr)

[0 1 2 3 4 5]


In [114]:
# 27. Replace the second element with 99.

arr[1] = 99
print(arr)

[ 0 99  2  3  4  5]


In [118]:
# 28. Update a slice of elements from index 2 to 4 with 0.

arr[2:5] = 0
print(arr)

[ 0 99  0  0  0  5]


In [125]:
# 29. Set the last three elements to 10.

arr[-1:-4:-1] = 10
print(arr)

[ 0 99  0 10 10 10]


In [126]:
# 30. Updating a 2D Array

arr.reshape(2,3)

array([[ 0, 99,  0],
       [10, 10, 10]])

In [129]:
# 31. Create a 3x3 NumPy array with values from 1 to 9.

arr = np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [131]:
# 32. Replace the second row with all 5s

arr[1,:] = 5
print(arr)

[[1 2 3]
 [5 5 5]
 [7 8 9]]


In [134]:
# 33. Update the third column with values [8, 9, 10].

arr[:,2] = [8,9,10]
print(arr)

[[ 1  2  8]
 [ 5  5  9]
 [ 7  8 10]]


In [135]:
# 34. Using a Condition to Modify Elements:

arr[arr>5] = 0
print(arr)

[[1 2 0]
 [5 5 0]
 [0 0 0]]


In [141]:
# 35. Create a NumPy array with random numbers from 1 to 20.

np.random.seed(42)

arr = np.random.randint(1,20,10)
print(arr)

[ 7 15 11  8  7 19 11 11  4  8]


In [142]:
# 36. Set all values greater than 10 to zero.

arr[arr>10] = 0
print(arr)

[7 0 0 8 7 0 0 0 4 8]


In [145]:
# 37. Create an array [10, 20, 30, 40] and insert 25 at index 2.

arr = np.array([10, 20, 30, 40])
arr = np.insert(arr,2,25)
print(arr)

[10 20 25 30 40]


In [149]:
# 38. Create an array [1, 2, 3] and append [4, 5, 6] to it.

arr = np.array([1,2,3])
arr = np.append(arr,(4,5,6))
print(arr)

[1 2 3 4 5 6]


In [158]:
# 39. Create an array [5, 10, 15, 20, 25] and delete the third element.

arr = np.array([5, 10, 15, 20, 25])
arr = np.delete(arr,2)
print(arr)

[ 5 10 20 25]


In [159]:
# 40. Create an array from 1 to 12 and reshape it into a 3×4 matrix.

arr = np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [173]:
# 41. Create a 2D array and flatten it using np.ravel() and .flatten().

arr = np.arange(1,7).reshape(3,2)
print(f'Original array:\n{arr}\n')
print(f'Ravel:\n{np.ravel(arr)}\n')  #returns a view of the array when possible
print(f'Flatten:\n{arr.flatten()}')  #always returns a copy (changes won’t affect the original)

Original array:
[[1 2]
 [3 4]
 [5 6]]

Ravel:
[1 2 3 4 5 6]

Flatten:
[1 2 3 4 5 6]


In [176]:
# 42. Create a 3×3 matrix and find its transpose using np.transpose().

arr = np.arange(1,10).reshape(3,3)
print(np.transpose(arr))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [177]:
''' Create two arrays '''

' Create two arrays '

In [179]:
# 43. A = np.array([2, 4, 6]), B = np.array([1, 2, 3]).

a = np.array([2, 4, 6])
b = np.array([1, 2, 3])
print(b,a)

[1 2 3] [2 4 6]


In [192]:
# 44. Perform element-wise addition, subtraction, multiplication, and division.

print('Addition:', a+b)
print('Subtraction:', a-b)
print('Mutiplication:', a*b)
print('Division:', a/b)

Addition: [3 6 9]
Subtraction: [1 2 3]
Mutiplication: [ 2  8 18]
Division: [2. 2. 2.]


In [197]:
# 45. Create two 2×2 matrices and compute their dot product using np.dot() and @ operator.

a = np.array([[2, 4], [6,8]])
b = np.array([[1, 2], [5,9]])
print(np.dot(a,b))
print(a@b)

[[22 40]
 [46 84]]
[[22 40]
 [46 84]]


In [202]:
# # 46. Create an array with values [4, 8, 15, 16, 23, 42].
# 47. Compute sum, min, max, mean, median, variance, standard deviation, and correlation coefficient.

arr = np.array([4, 8, 15, 16, 23, 42])
print('Sum:', np.sum(arr))
print('Min:', np.min(arr))
print('Max:', np.max(arr))
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Variance:', np.var(arr))
print('Standard deviation:', np.std(arr))
print('Correlation coefficient:', np.corrcoef(arr))

Sum: 108
Min: 4
Max: 42
Mean: 18.0
Median: 15.5
Variance: 151.66666666666666
Standard deviation: 12.315302134607444
Correlation coefficient: 1.0


In [203]:
''' NumPy Vectorization '''

' NumPy Vectorization '

In [207]:
# 48. Create a NumPy array of numbers from 1 to 10 and multiply all elements by 5 using vectorization (without using a loop).

arr = np.arange(1,11)
print(arr)
print(arr*5)

[ 1  2  3  4  5  6  7  8  9 10]
[ 5 10 15 20 25 30 35 40 45 50]


In [208]:
# 49. Given two NumPy arrays:
# A = np.array([1, 2, 3, 4])
# B = np.array([10, 20, 30, 40])
# Find the element-wise sum using vectorized operation (no loops).

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(a+b)

[11 22 33 44]


In [210]:
# 50. Create a NumPy array of numbers from 1 to 10.
# Replace all even numbers with 0 using vectorization (no loops).

arr = np.arange(1,11)
arr[arr % 2 == 0] = 0
print(arr)

[1 0 3 0 5 0 7 0 9 0]


In [211]:
''' Vectorization vs Loops '''

' Vectorization vs Loops '

In [229]:
# 51. Write two ways to calculate the square of each element of an array [1, 2, 3, 4, 5]:
# Using a for loop
# Using NumPy vectorization
# Compare the number of lines and simplicity.

arr = np.array([1, 2, 3, 4, 5])

#using for loop
print('Using for loop:')
for i in arr:
    i = i**2
    print(i, end=' ')

#Using NumPy vectorization
print('\nUsing NumPy vectorization:')
print(arr**2)

# Compare the number of lines and simplicity.

# For loop:   - 3,4 lines
#             - More Verbose
#             - Slower(iterates element by element)

# NumPy vectorization:    - 1 line code
#                         - Very verbose
#                         - Faster

Using for loop:
1 4 9 16 25 
Using NumPy vectorization:
[ 1  4  9 16 25]


In [272]:
# 52. Create a NumPy array of 10 random numbers.
# Find how many numbers are greater than 5 using:
# for loop
# A vectorized condition


arr = np.random.randint(1,50,10)
print(f'Original matrix: {arr}\n')

print('Using for loop:')
#using for loop
for i in arr:
    if i > 5:
        print(i, end=' ')

# A vectorized condition
print('\n\nUsing vectorized condition:')
print(arr[arr>5])

Original matrix: [32 23 33  3 18 25 42 31  3 40]

Using for loop:
32 23 33 18 25 42 31 40 

Using vectorized condition:
[32 23 33 18 25 42 31 40]
