### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [1]:
import numpy as np

###### 1. Write a NumPy program to find the missing data in a given array.

In [9]:
arr = np.array([[ 3,2,np.nan,1],
                [10,12,10,9],
                [ 5,np.nan,1,np.nan]])

arr_missing = np.isnan(arr)

print(f'Original array:\n{arr}\n')
print(f'Missing data of te said array:\n{arr_missing}')

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Missing data of te said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [ ]:
## sample output

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [16]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2, 6, 4, 5])

print(f'First array:\n{arr1}\nSecond array:\n{arr2}')
print(f'Element-wise equal or not:\n{arr1==arr2}')

First array:
[1 2 3 4 5]
Second array:
[1 2 6 4 5]
Element-wise equal or not:
[ True  True False  True  True]


###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [39]:
arr = np.arange(0,16).reshape(4,4)
print(f'Origina array:\n{arr}\n')
arr_swapped = arr.copy()
arr_swapped[[0,-1]] = arr_swapped[[-1,0]]
print(f'New array after swapping first and last rows of the said array:\n{arr_swapped}')

Origina array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [ ]:
## sample output

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [44]:
lst = [1,2,3,4,5]
tup = (6,7,8,9,10)
arr1 = np.array(lst)
arr2 = np.array(tup)
print(f'List to array: {arr1}')
print(f'Tuple to array: {arr2}')

List to array: [1 2 3 4 5]
Tuple to array: [ 6  7  8  9 10]


###### 5. Write a NumPy program to find common values between two arrays.

In [50]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,1,8])
arr_common = np.intersect1d(arr1,arr2)

print(f'First array: {arr1}\nSecond array: {arr2}')
print(f'Common values between two arrays: {arr_common}')

First array: [1 2 3 4 5]
Second array: [5 6 7 1 8]
Common values between two arrays: [1 5]


###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [52]:
arr = np.arange(1,7)
print(f'Original array:\n{arr}')

arr1 = arr.reshape(3,2)
arr2 = arr.reshape(2,3)
print(f'Reshaped 3x2:\n{arr1}')
print(f'Reshaped 2x3:\n{arr2}')

Original array:
[1 2 3 4 5 6]
Reshaped 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshaped 2x3:
[[1 2 3]
 [4 5 6]]


In [ ]:
### sample output

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [55]:
arr = np.array([10,10,20,10,20,20,20,30,30,50,40,40])
print(f'Original array:\n{arr}')

unique_values, counts = np.unique(arr, return_counts=True)
frequency = np.array([unique_values, counts])

print(f'Frequency of unique values of the said array:\n{frequency}')

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


In [ ]:
## sample output

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [61]:
p = np.array([[0,0,0],
                 [1,2,3],
                 [4,5,6]])
q = np.array([10,11,12])

print(f'Original arrays:\nArray-1\n{p}\nArray-2:\n{q}\n')
print(f'New Array:\n{p+q}')

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2:
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


In [ ]:
## sample output

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [65]:
arr = np.arange(0,16).reshape((4, 4))
print(f"Original array:\n{arr}\n")
print(f"Extracted data: Second row:\n{arr[1,:]}")

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row:
[4 5 6 7]


In [62]:
## sample code

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [69]:
arr = np.arange(0,16).reshape((4, 4))
print(f"Original array:\n{arr}\n")
print(f'Extracted data: Third and fourth elements of the first and second rows:\n{arr[0:2,2:4]}')

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows:
[[2 3]
 [6 7]]


In [ ]:
## sample output

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [75]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
print(f'Today: {today}\nYesterday: {yesterday}\nTomorrow: {tomorrow}')

Today: 2025-12-30
Yesterday: 2025-12-29
Tomorrow: 2025-12-31


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [79]:
may2017 = np.datetime64('2017-05')
first_monday = np.busday_offset(may2017, 0, roll='forward', weekmask='Mon')
print(f'First Monday in May 2017:\n{first_monday}')

First Monday in May 2017:
2017-05-01


In [ ]:
## sample output

First Monday in May 2017:
2017-05-01
