In [4]:
import numpy as np

In [10]:
# Q1. Create a 1D NumPy array of integers from 1 to 10.

arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [18]:
# Q2. Create a 2D array of shape (3, 3) containing numbers from 1 to 9.

arr = np.random.randint(1,10,(3,3))
print(arr)

[[4 6 5]
 [6 8 5]
 [4 9 8]]


In [33]:
# Q3. Display the dimensions, shape, size, and data type of a NumPy array.

arr = np.random.randint(1,10,(3,3))
print(f'Array:\n{arr}\n{'-'*10}')
print(f'Dimensions: {arr.ndim}\n{'-'*10}')
print(f'Shape: {arr.shape}\n{'-'*10}')
print(f'Size: {arr.size}\n{'-'*10}')
print(f'Data Type: {arr.dtype}')

Array:
[[6 1 6]
 [1 6 7]
 [6 9 4]]
----------
Dimensions: 2
----------
Shape: (3, 3)
----------
Size: 9
----------
Data Type: int32


In [34]:
# Q4. Create an array of 10 elements, all initialized with the value 5.

arr = np.full(10,5)
print(arr)

[5 5 5 5 5 5 5 5 5 5]


In [46]:
# Q5. Create an array of even numbers between 10 and 30.

arr = np.random.randint(10,30,10)
print(f'Array: {arr}')
print(f'Even numbers: {arr[(arr % 2 == 0)]}')

Array: [22 29 18 29 22 23 27 29 13 19]
Even numbers: [22 18 22]


In [ ]:
# Given array:

# import numpy as np

# arr = np.array([[10, 20, 30, 40],
#                		    [50, 60, 70, 80],
#                                     [90, 100, 110, 120],
#                                     [130, 140, 150, 160]])

In [54]:
# Q6.Print the element in the 3rd row and 2nd column.

arr = np.array([[10, 20, 30, 40],
               	[50, 60, 70, 80],
                [90, 100, 110, 120],
                [130, 140, 150, 160]])

print("Element at 3rd row, 2nd column:", arr[2, 1])

Element at 3rd row, 2nd column: 100


In [55]:
# Q7. Extract the first row of the array.

print(f'First row of the array: {arr[0,:]}')

First row of the array: [10 20 30 40]


In [57]:
# Q8. Extract the last column of the array.
print(f'Last row of the array: {arr[-1,:]}')

Last row of the array: [130 140 150 160]


In [59]:
# Q9. Extract the 2×2 subarray from the top-left corner.
print(arr[:2, :2])

[[10 20]
 [50 60]]


In [68]:
# Q10. Extract the 3×2 subarray consisting of the last 3 rows and first 2 columns.

print(arr[1:4,0:2])

[[ 50  60]
 [ 90 100]
 [130 140]]


In [66]:
# Q11. Extract every second element from the first row.

print(arr[0, ::2])

[10 30]


In [70]:
# Q12. Extract the array elements at positions (0,1), (2,3), and (3,0) using fancy indexing.

print(arr[[0,2,3], [1,3,0]])

[ 20 120 130]


In [72]:
# Q13. Slice the array to get the 2×2 subarray from the bottom-right corner.

print(arr[-2:,-2:])

[[110 120]
 [150 160]]
